stages:
  - build
  - test
  - deploy

executor:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "master"
  image: ${CI_REGISTRY_IMAGE}:latest
  tags:
    - docker
  script:
    - python3 executor.py


build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "test" && $CI_PIPELINE_SOURCE != "schedule"
      changes:
        - "*.py"
        - Dockerfile
  tags:
    - build
    - docker-runtime
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
    - docker build --tag ${CI_REGISTRY_IMAGE}:$CI_COMMIT_BRANCH .
    - docker push ${CI_REGISTRY_IMAGE}:$CI_COMMIT_BRANCH

# Teste com apoio do projeto informado em "$TESTE_PROJID"
teste:
  tags:
    - trigger
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}
  rules:
    - if: $CI_COMMIT_BRANCH == "test" && $CI_PIPELINE_SOURCE != "schedule"
  variables:
    SMTP_SUBJECT: GitlabJob_Teste
  stage: test
  script:
    - echo "Testes unitários"
    - export SMTP_TO=$GITLAB_USER_EMAIL
    - export PROJECT_ID=$TESTE_PROJID
    - export SMTP_SUBJECT="GitlabJob_Teste"
    - export TESTE_TOKENTRIG="ceacca74cb3fdeed161d8552870c63"
    - export GROUP_ID=$TESTE_GRPID
    - python3 -m unittest test*.py
    - sleep 5
    - echo "Teste de integração"
    - python3 executor.py

prod:build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"
      changes:
        - "*.py"
        - Dockerfile
  tags:
    - build
    - docker-runtime
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
    - docker build --tag ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest
