services:
  - docker:dind

stages:
  - build
  - run

executor:
  stage: run
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && ( $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main" )
  image: ${CI_REGISTRY_IMAGE}:latest
  tags:
    - gitlab-org-docker
  script:
    - ""

prod:build:
  stage: build
  rules:
    - if: ( $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main" ) && $CI_PIPELINE_SOURCE != "schedule"
      changes:
        - "*.rs"
        - Dockerfile
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
    - docker build --tag ${CI_REGISTRY_IMAGE}:latest .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}:latest
