[package]
name = "gitlabjob"
version = "0.1.0"
edition = "2021"
authors = ["Dyego <dyegomb@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
envy = "0.4"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
env_logger = "0.10"
merge = "0.1"
lettre = "0.10"
email_address = "0.2"
futures = "0.3"