[package]
name = "gitlabjob"
version = "1.1.0"
edition = "2021"
authors = ["Dyego <dyegomb@gmail.com"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
env_logger = "0.10"
configloader = { path = "./configloader"}
mailsender = { path = "./mailsender" }
gitlabapi = { path = "./gitlabapi" }

[dev-dependencies]
env_logger = "0.10"
serde_json = "1.0"


[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.jemallocator]
version = "0.5"

[workspace]
members = [
    "gitlabapi",
    "configloader",
    "mailsender"
]