name: Build

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          pull: true
          push: true
          # cache-from: type=registry,ref=myorg/myrepository:latest
          # cache-to: type=inline
          tags: ghcr.io/${{ github.repository }}:latest

  # musl_builder:
  #   name: Musl build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: x86_64-unknown-linux-musl
  #         override: true
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: build
  #         args: --release --target x86_64-unknown-linux-musl

  gnulinux_builder:
    name: GNU/Linux build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v3
        with:
          name: gitlabjob-bin
          path: target/release/gitlabjob
